# ansible-playbook -i servers --ask-pass --ask-become-pass vim.yml --limit=virtual
# ansible-playbook --connection=local -i systems vim.yml --limit=localhost
- hosts: all
  become: yes
  vars:
    vim_user: defaultuser
    vim_group: defaultuser
  roles:
    - role: guts

