---

- name: Add vimrc file settings
  ansible.builtin.template:
    src: vimrc.j2
    dest: /home/tjp/.vimrc
    owner: "{{ vim_user }}"
    group: "{{ vim_group }}"

- name: Create vimrc support directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ vim_user }}"
    group: "{{ vim_group }}"
  loop:
    - "/home/{{ vim_user }}/.vim/backup"
    - "/home/{{ vim_user }}/.vim/undo"
    - "/home/{{ vim_user }}/.vim/swap"
